apiVersion: v1
kind: Service
metadata:
  name: pulse-app
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: pulse-app
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: pulse-app
  ports:
    - name: http
      port: 80
      targetPort: 8000
