apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: pulse-worker
  namespace: {{ .Release.Namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: pulse-worker
  minReplicas: {{ .Values.worker.hpa.minReplicas }}
  maxReplicas: {{ .Values.worker.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.worker.hpa.targetCPUUtilizationPercentage }}
